name: Build and deploy PHP app to Azure Web App - collegecomplaintsys

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup PHP (optional, but good for composer projects)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Run composer install if composer.json exists
      - name: Install dependencies if composer.json exists
        run: |
          if [ -f "composer.json" ]; then
            composer validate --no-check-publish
            composer install --prefer-dist --no-progress
          fi

      # Deploy directly from repo
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'collegecomplaintsys'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
