name: Build and deploy PHP app to Azure Web App - collegecomplaintsys

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Install dependencies if composer.json exists
      - name: Install dependencies if composer.json exists
        run: |
          if [ -f "composer.json" ]; then
            composer validate --no-check-publish
            composer install --prefer-dist --no-progress
          fi

      # Log in to Azure using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6372538AC9C444F185872915C7446B3D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2B14C0423A974F1BBBBC79A5102E8EBD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_12F62D6579DD46FB82933EA319D8A624 }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'collegecomplaintsys'   # Must match EXACT Azure App Service name
          slot-name: 'Production'
          package: .
